### ISSUE TITLE
[建议]技术型建议

### ISSUE THREAD

**Issue by qwas982** [tjy-gitnub/win12#220]
## 描述

将底座从`v8`换成`wasm`.

## 方案

工程可以一步步实现,
1,打通一条编译为机器码的通路.
2, `js `→ `wasm `→ `llvm ir`.
3,写一个`桥`,在Linux启动后通过这个`桥`连通X服务器或Wayland 与本项目`win12 UI`, `桥`一样可以用`js`实现.

## 其他

这个建议的目的是希望能运行在本地,获得原生流程的速度.
并且又可以创造一个新的Linux发行版. (希望把输入法完善

**Comment by travisgu** [comment]
这个项目的目标应该不是要搞一套能真正生产使用的OS吧，更多的是演示功能

**Comment by tjy-gitnub** [comment]
呐，我们计划的是套windows呢~
