### ISSUE TITLE
点击登录就蓝屏

### ISSUE THREAD

**Issue by 431658** [tjy-gitnub/win12#482]
点击登录就蓝屏
![mmexport1727501245389](https://github.com/user-attachments/assets/e700c887-13c7-4e57-9431-fe1ba597ba27)
![mmexport1727501247365](https://github.com/user-attachments/assets/4fb76831-9afc-4fd8-b8ca-0acd3f755627)

**Comment by User782Tec** [comment]
设计如此，并非漏洞

**Comment by User782Tec** [comment]
设计如此，并非漏洞

**Comment by Mbilse** [comment]
> 点击登录就蓝屏
> ![mmexport1727501245389](https://github.com/user-attachments/assets/e700c887-13c7-4e57-9431-fe1ba597ba27)
> ![mmexport1727501247365](https://github.com/user-attachments/assets/4fb76831-9afc-4fd8-b8ca-0acd3f755627)

要不然跳转到logon.live
